/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once
#define VIAL_KEYBOARD_UID {0x38, 0xAA, 0x38, 0x33, 0xE6, 0xDF, 0x5A, 0x60}
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define DYNAMIC_KEYMAP_MACRO_COUNT 12
#define TAP_CODE_DELAY 30
#define MOUSEKEY_MOVE_DELTA 2
/* RP2040 config */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
/* Lighting */
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB
#define WS2812_RGBW
#define WS2812_DI_PIN GP0
#define RGB_MATRIX_LED_COUNT 9
#define RGBLIGHT_LED_COUNT 9
#define RGB_MATRIX_SLEEP
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
/* Lighting effects */
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_PIXEL_FLOW
